apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app: my-webapp
spec:
  containers:
    - name: webapp
      image: richardchesterwood/k8s-fleetman-webapp-angular:release0
      ports:
        - name: webapp-port
          containerPort: 80
